# Generated by Django 5.0.4 on 2024-05-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_order_data_alter_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/commodities'),
        ),
    ]
